[build]
builder = "DOCKERFILE"
watchPatterns = ["/client/**/*"]
dockerfilePath = "client/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
