version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain Server dependencies for npm
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"  
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
  # Maintain Server dependencies for Composer
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "weekly"
