version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain Server dependencies for npm
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/infra"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/db-seed"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/tests/e2e-tests"
    schedule:
      interval: "daily"
  # Maintain Server dependencies for Composer
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "daily"
