version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain Server dependencies for npm
  - package-ecosystem: "npm"
    directory: "/projects/graphql-server"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/projects/client"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/projects/cron-jobs"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/projects/db-seed"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/packages/infra"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/packages/db-schemas"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/packages/data-cleaner"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/tests/e2e-tests"
    schedule:
      interval: "monthly"
  # Maintain Server dependencies for Composer
  - package-ecosystem: "docker"
    directory: "/projects/graphql-server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/projects/client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/projects/db-seed"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/projects/cron-jobs"
    schedule:
      interval: "weekly"
