version: '3.8'

services:
  scipio-db:
    container_name: scipio-db
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: scipio-test
    volumes:
      - dbdata:/data/db
    ports:
      - '27017:27017'
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.runCommand(\"ping\").ok" ]
      interval: 10s
      timeout: 5s
      retries: 5
  scipio-redis:
    container_name: scipio-redis
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  scipio-graphql-server:
    container_name: scipio-server
    build:
      context: projects/graphql-server
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    environment:
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      MONGO_DB_URI: 'mongodb://root:password@scipio-db:27017/scipio-test?authSource=admin'
      REDIS_URI: 'redis://default:password@scipio-redis:6379'
      PORT: '8080'
      NODE_ENV: 'test'
      WEB_URL: 'http://localhost:3000'
    ports:
      - '8080:8080'
    depends_on:
      scipio-db:
        condition: service_healthy
      scipio-redis:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ping || exit 1
      interval: 5s
      timeout: 3s
      retries: 20
  scipio-client:
    container_name: scipio-client
    build:
      context: projects/client
      args:
        VITE_ENVIRONMENT: "test"
        VITE_FIREBASE_API_KEY: ${FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
        VITE_FIREBASE_APP_ID: ${FIREBASE_APP_ID}
        VITE_API_BASE_URL: "http://localhost:8080"
        SENTRY_CLIENT_PROJECT: "scipio-client-staging"
    ports:
      - '3000:80'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1
      interval: 5s
      timeout: 3s
      retries: 20
  scipio-db-seed:
    container_name: scipio-db-seed
    build:
      context: projects/db-seed
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    environment:
      MONGO_DB_URI: 'mongodb://root:password@scipio-db:27017/scipio-test?authSource=admin'
    depends_on:
      scipio-db:
        condition: service_healthy
  scipio-cron-jobs:
    container_name: scipio-cron-jobs
    build:
      context: projects/cron-jobs
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    environment:
      MONGO_DB_URI: 'mongodb://root:password@scipio-db:27017/scipio-test?authSource=admin'
      REDIS_URI: 'redis://default:password@scipio-redis:6379'
      EMAIL_SENDER: 'no-reply@scipiofinances.com'
      EMAIL_AUTH_DOMAIN: 'scipio-mailhog'
      EMAIL_AUTH_PORT: '1025'
      EMAIL_AUTH_USER: 'user'
      EMAIL_AUTH_PASS: 'password'
    depends_on:
      scipio-db:
        condition: service_healthy
      scipio-redis:
        condition: service_healthy
  scipio-mailhog:
    container_name: scipio-mailhog
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
      - '1025:1025'
volumes:
  dbdata:
  redisdata:
networks:
  default:
    driver: bridge
    name: scipio
