[build]
builder = "DOCKERFILE"
watchPatterns = ["/projects/graphql-server/**/*"]
dockerfilePath = "/projects/graphql-server/Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
