[build]
builder = "DOCKERFILE"
watchPatterns = ["projects/cron-jobs/**/*"]
dockerfilePath = "projects/cron-jobs/Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
