[build]
builder = "DOCKERFILE"
watchPatterns = ["/projects/client/**/*"]
dockerfilePath = "/projects/client/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
