version: '3.8'

services:
  scipio-db:
    container_name: scipio-db
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - dbdata:/data/db
  scipio-server:
    build:
      context: ../server
    environment:
      FIREBASE_CLIENT_EMAIL: ''
      FIREBASE_PRIVATE_KEY: ''
      FIREBASE_PROJECT_ID: ''
      MONGO_DB_PROTOCOL: 'mongo'
      MONGO_DB_HOST: 'scipio-db'
      MONGO_DB_PORT: '27017'
      MONGO_DB_NAME: 'scipio-test'
      MONGO_DB_USER: 'root'
      MONGO_DB_PASSWORD: 'password'
      PORT: '8080'
      ENVIRONMENT: 'test'
    ports:
      - '8080:8080'
    depends_on:
      scipio-db:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ping || exit 1
      interval: 5s
      timeout: 3s
      retries: 20
  scipio-client:
    build:
      context: ../client
    ports:
      - '3000:80'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  dbdata:
networks:
  default:
    driver: bridge
    name: scipio