name: DB Seed

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Environment Target"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  db-seed:
    name: "Database seed for ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: projects/db-seed
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@knightprogrammers'
      - name: Cache DB Seed node modules
        uses: actions/cache@v3
        with:
          path: projects/db-seed/node_modules
          key: db-seed-node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: db-seed-node_modules-
      - name: Install DB Seed dependencies
        run:  npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run DB Seed build typescript
        run:  npm run build
      - name: Setup environment vars
        env:
          SECRETS_VARS: ${{ toJson(secrets) }}
        run: echo "$SECRETS_VARS" > "secrets.json"
      - name: Install JSON to ENV lib
        run: npm install -g json-to-env
      - name: Generate .env file
        run: |
          json-to-env secrets.json .env
          sed -i -e 's/export //g' .env
      - name: Run DB Seed
        run:  npm run start
