name: Continuous Integration - On Deployment

on:
  deployment_status:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  e2e-tests:
    name: "E2E Tests"
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy
    env:
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set url variables
        id: set-url-variables
        run: |
          if [ ${{ github.event.deployment.environment }} != 'Staging' ]; then
            echo "Environment Test"
            echo "BASE_URL=https://scipio-client-test-${{ github.event.workflow_run.pull_requests[0].number }}.up.railway.app" >> $GITHUB_ENV
            echo "API_BASE_URL=https://scipio-server-test-${{ github.event.workflow_run.pull_requests[0].number }}.up.railway.app" >> $GITHUB_ENV
            echo "{environment_variable_name}={value}" >> $GITHUB_ENV
          else
            echo "Environment Staging"
            echo "BASE_URL=https://staging.scipiofinances.com" >> $GITHUB_ENV
            echo "API_BASE_URL=https://staging-api.scipiofinances.com" >> $GITHUB_ENV
          fi
        shell: bash
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: tests/e2e-tests/node_modules
          key: e2e-tests-node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: e2e-tests-node_modules-
      - name: Install Dependencies
        run: |
          cd tests/e2e-tests
          npm install
      - name: Install Playwright Browsers
        run: |
          cd tests/e2e-tests
          npx playwright install --with-deps
      - name: Run Tests
        env:
          BASE_URL: ${{ env.BASE_URL }}
          API_BASE_URL: ${{ env.API_BASE_URL }}
          TEST_USER_EMAIL:  ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASS: ${{ secrets.TEST_USER_PASS }}
          TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
        run: |
          cd tests/e2e-tests
          npm run smoke-test
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: e2e-report
          path: tests/e2e-tests/playwright-report/
          retention-days: 7
