name: Continuous Integration - On Deployment

on:
  deployment_status:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  packages: read

jobs:
  e2e-tests-smoke:
    name: "E2E Tests - Smoke"
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy
    env:
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set url variables
        id: set-url-variables
        run: |
          case "${{ github.event.deployment.environment }}" in
          Production) echo "Environment Production"
            echo "BASE_URL=https://scipio-client-production.up.railway.app" >> $GITHUB_ENV
            echo "API_BASE_URL=https://scipio-server-production.up.railway.app" >> $GITHUB_ENV
            ;;
          Staging) echo "Environment Staging"
            echo "BASE_URL=https://staging.scipiofinances.com" >> $GITHUB_ENV
            echo "API_BASE_URL=https://staging-api.scipiofinances.com" >> $GITHUB_ENV
            ;;
          *) echo "Environment Test"
            echo "BASE_URL=https://scipio-client-test-${{ github.event.workflow_run.pull_requests[0].number }}.up.railway.app" >> $GITHUB_ENV
            echo "API_BASE_URL=https://scipio-server-test-${{ github.event.workflow_run.pull_requests[0].number }}.up.railway.app" >> $GITHUB_ENV
            ;;
          esac
        shell: bash
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: tests/e2e-tests/node_modules
          key: e2e-tests-node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: e2e-tests-node_modules-
      - name: Install Dependencies
        run: |
          cd tests/e2e-tests
          npm install
      - name: Install Playwright Browsers
        run: |
          cd tests/e2e-tests
          npx playwright install --with-deps
          npx playwright install chrome
      - name: Run Tests
        env:
          BASE_URL: ${{ env.BASE_URL }}
          API_BASE_URL: ${{ env.API_BASE_URL }}
          TEST_USER_EMAIL:  ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASS: ${{ secrets.TEST_USER_PASS }}
          TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
          DD_CIVISIBILITY_AGENTLESS_ENABLED: true
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_SITE: ${{ secrets.DD_SITE }}
          NODE_OPTIONS: "-r dd-trace/ci/init"
          DD_ENV: ${{ github.event.deployment.environment }}
          DD_SERVICE: "Scipio"
        run: |
          cd tests/e2e-tests
          npm run smoke-test
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: e2e-report
          path: tests/e2e-tests/playwright-report/
          retention-days: 7
