name: Continuous Integration - On Merge to Main

on:
  push:
    branches: [ 'main' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  checks: write
  statuses: write
  contents: write
  packages: read
  pull-requests: write


jobs:
  server-build-check:
    name: "Server - Build Check"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/graphql-server
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@knightprogrammers'
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: projects/graphql-server/node_modules
          key: graphql-server-node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: graphql-server-node_modules-
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run lint
        run: npm run lint
  client-build-check:
    name: "Client - Build Check"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/client
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: projects/client/node_modules
          key: client-node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: client-node_modules-
      - name: Install Dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run prettier
        run: npm run prettier
  db-seed-build-check:
    name: "DB-Seed - Build Check"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/db-seed
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@knightprogrammers'
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: projects/db-seed/node_modules
          key: db-seed-node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: db-seed-node_modules-
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run lint
        run: npm run lint
  infra-build-check:
    name: "Infra - Build Check"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/infra
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: packages/infra/node_modules
          key: infra-node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: infra-node_modules-
      - name: Install Dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  e2e-tests:
    name: "E2E Tests"
    runs-on: ubuntu-latest
    needs: [ server-build-check, client-build-check, db-seed-build-check, infra-build-check ]
    env:
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Dockers
        run: docker compose up --detach --wait --build
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: tests/e2e-tests/node_modules
          key: e2e-tests-node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: e2e-tests-node_modules-
      - name: Install Dependencies
        run: |
          cd tests/e2e-tests
          npm ci
      - name: Install Playwright Browsers
        run: |
          cd tests/e2e-tests
          npx playwright install --with-deps
      - name: Run Tests
        env:
          BASE_URL: http://localhost:3000
          API_BASE_URL: http://localhost:8080
          DD_CIVISIBILITY_AGENTLESS_ENABLED: true
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_SITE: ${{ secrets.DD_SITE }}
          NODE_OPTIONS: "-r dd-trace/ci/init"
          DD_ENV: "Test"
          DD_SERVICE: "Scipio"
        run: |
          cd tests/e2e-tests
          npm run regression-test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-report
          path: tests/e2e-tests/playwright-report/
          retention-days: 7
  deploy-services:
    name: "Deploy Services"
    runs-on: ubuntu-latest
    needs: [ e2e-tests ]
    environment:
      name: Staging
      url: https://staging.scipiofinances.com
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@knightprogrammers'
          always-auth: true
      - name: Install scipio-infra globaly
        run: npm install -g @knightprogrammers/scipio-infra
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install railway cli
        run: npm i -g @railway/cli
      - name: Deploy server service
        run: scipio-infra deploy -s server -e staging
        env:
          RAILWAY_USER_TOKEN: ${{ secrets.RAILWAY_USER_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      - name: Deploy client service
        run: scipio-infra deploy -s client -e staging
        env:
          RAILWAY_USER_TOKEN: ${{ secrets.RAILWAY_USER_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      - name: Create Sentry release for Client
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: "scipio-finances"
          SENTRY_PROJECT: ${{ secrets.SENTRY_CLIENT_PROJECT }}
          SENTRY_URL: https://sentry.io/
        with:
          environment: staging
          working_directory: './projects/client/'
      - name: Create Sentry release for Server
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: "scipio-finances"
          SENTRY_PROJECT: ${{ secrets.SENTRY_SERVER_PROJECT }}
          SENTRY_URL: https://sentry.io/
        with:
          environment: staging
          working_directory: './projects/graphql-server/'

