name: Pull Request Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  packages: read

jobs:
  delete-test-env:
    name: "Delete Test Environment"
    runs-on: ubuntu-latest
    env:
      RAILWAY_USER_TOKEN: ${{ secrets.RAILWAY_USER_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@knightprogrammers'
          always-auth: true
      - name: Install scipio-infra globaly
        run: npm install -g @knightprogrammers/scipio-infra
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete environment
        run: scipio-infra environment-delete "test-${{ github.event.number }}"
