name: Release Infra Lib version

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Type of Release
        options:
          - major
          - minor
          - patch
        default: patch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write
  repository-projects: write

jobs:
  release-new-version:
    name: ""
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/infra
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@knightprogrammers'
      - name: Install dependencies
        run:  npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Increase version
        run:  npm version ${{inputs.type}}
      - name: Publish version
        run:  npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Config git user
        shell: bash
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Build temporary branch name
        id: temp_branch
        shell: bash
        run: |
          TEMP_BRANCH_PREFIX="infra-version_${{ github.run_id }}-${{ github.run_attempt }}"
          echo "::set-output name=value::$base_branch"
          echo "value=$TEMP_BRANCH_PREFIX" >> $GITHUB_OUTPUT
      - name: Commit and push the changes to a temporary branch
        shell: bash
        run: |
          git checkout -b ${{ steps.temp_branch.outputs.value }}
          git add --all
          git commit -m "Maint: Upgrade version"
          git push -u origin ${{ steps.temp_branch.outputs.value }}
      - name: Create Pull Request
        shell: bash
        run: |
          gh pr create --base ${{ github.ref_name }} --head ${{ steps.temp_branch.outputs.value }} --title "Maint: Infra Lib Release" --body ""
