name: Reset Demo Data


on:
  workflow_dispatch:
    inputs:
      environment:
        default: "Staging"
        type: environment
        description: "Environment Target"
        required: true
  schedule:
    - cron: '0 3 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  data-cleaner:
    name: Reset Demo Data - Env ${{ inputs.environment || 'Staging' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'Staging' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@knightprogrammers'
      - name: Install Data Cleaner dependencies
        run: |
          cd projects/data-cleaner
          npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Data Cleaner build typescript
        run: |
          cd projects/data-cleaner
          npm run build
      - name: Run Data Cleaner
        run: |
          cd projects/data-cleaner
          npm run start
        env:
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          LOG_LEVEL: "info"
          WHITELIST_FIREBASE_IDS: ${{ secrets.WHITELIST_FIREBASE_IDS }}
      - name: Install DB Seed dependencies
        run: |
          cd projects/db-seed
          npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run DB Seed build typescript
        run: |
          cd projects/db-seed
          npm run build
      - name: Run DB Seed Generate Demo
        run: |
          cd projects/db-seed
          npm run gen-demo
        env:
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          LOG_LEVEL: "info"
          USER_FIREBASE_ID: ${{ secrets.USER_FIREBASE_ID }}
